name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image to ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin [039434644707.dkr.ecr.us-east-2.amazonaws.com/coin-custody](http://039434644707.dkr.ecr.us-east-2.amazonaws.com/coin-custody)
          docker build -t my-lambda-image-test -f coin-custody-image.dockerfile .
          docker tag my-lambda-image-test:latest 865443971782.dkr.ecr.us-east-2.amazonaws.com/coin-custody:latest
          docker push 865443971782.dkr.ecr.us-east-2.amazonaws.com/coin-custody:latest
          
      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name lambda-test --image-uri 865443971782.dkr.ecr.us-east-2.amazonaws.com/coin-custody:latest
